// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: nodeward_l1sec.proto

package l1sec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nodeward_Register_FullMethodName       = "/runos.nodeward.proto.l1sec.Nodeward/Register"
	Nodeward_ServerRegister_FullMethodName = "/runos.nodeward.proto.l1sec.Nodeward/ServerRegister"
)

// NodewardClient is the client API for Nodeward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodewardClient interface {
	Register(ctx context.Context, in *NodeRegistrationRequest, opts ...grpc.CallOption) (*NodeRegistrationResponse, error)
	ServerRegister(ctx context.Context, in *ServerRegistrationRequest, opts ...grpc.CallOption) (*ServerRegistrationResponse, error)
}

type nodewardClient struct {
	cc grpc.ClientConnInterface
}

func NewNodewardClient(cc grpc.ClientConnInterface) NodewardClient {
	return &nodewardClient{cc}
}

func (c *nodewardClient) Register(ctx context.Context, in *NodeRegistrationRequest, opts ...grpc.CallOption) (*NodeRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeRegistrationResponse)
	err := c.cc.Invoke(ctx, Nodeward_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) ServerRegister(ctx context.Context, in *ServerRegistrationRequest, opts ...grpc.CallOption) (*ServerRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerRegistrationResponse)
	err := c.cc.Invoke(ctx, Nodeward_ServerRegister_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodewardServer is the server API for Nodeward service.
// All implementations must embed UnimplementedNodewardServer
// for forward compatibility.
type NodewardServer interface {
	Register(context.Context, *NodeRegistrationRequest) (*NodeRegistrationResponse, error)
	ServerRegister(context.Context, *ServerRegistrationRequest) (*ServerRegistrationResponse, error)
	mustEmbedUnimplementedNodewardServer()
}

// UnimplementedNodewardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodewardServer struct{}

func (UnimplementedNodewardServer) Register(context.Context, *NodeRegistrationRequest) (*NodeRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedNodewardServer) ServerRegister(context.Context, *ServerRegistrationRequest) (*ServerRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerRegister not implemented")
}
func (UnimplementedNodewardServer) mustEmbedUnimplementedNodewardServer() {}
func (UnimplementedNodewardServer) testEmbeddedByValue()                  {}

// UnsafeNodewardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodewardServer will
// result in compilation errors.
type UnsafeNodewardServer interface {
	mustEmbedUnimplementedNodewardServer()
}

func RegisterNodewardServer(s grpc.ServiceRegistrar, srv NodewardServer) {
	// If the following call pancis, it indicates UnimplementedNodewardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nodeward_ServiceDesc, srv)
}

func _Nodeward_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).Register(ctx, req.(*NodeRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_ServerRegister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).ServerRegister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_ServerRegister_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).ServerRegister(ctx, req.(*ServerRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nodeward_ServiceDesc is the grpc.ServiceDesc for Nodeward service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nodeward_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runos.nodeward.proto.l1sec.Nodeward",
	HandlerType: (*NodewardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Nodeward_Register_Handler,
		},
		{
			MethodName: "ServerRegister",
			Handler:    _Nodeward_ServerRegister_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeward_l1sec.proto",
}
