// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: nodeward_l1sec.proto

package l1sec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,25,opt,name=machineId,proto3" json:"machineId,omitempty"`
	Aid           string                 `protobuf:"bytes,30,opt,name=aid,proto3" json:"aid,omitempty"`
	Token         string                 `protobuf:"bytes,35,opt,name=token,proto3" json:"token,omitempty"`
	Os            string                 `protobuf:"bytes,40,opt,name=os,proto3" json:"os,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationRequest) Reset() {
	*x = NodeRegistrationRequest{}
	mi := &file_nodeward_l1sec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationRequest) ProtoMessage() {}

func (x *NodeRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l1sec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationRequest.ProtoReflect.Descriptor instead.
func (*NodeRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l1sec_proto_rawDescGZIP(), []int{0}
}

func (x *NodeRegistrationRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *NodeRegistrationRequest) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *NodeRegistrationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *NodeRegistrationRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

type NodeRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nid           string                 `protobuf:"bytes,50,opt,name=nid,proto3" json:"nid,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,60,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string                 `protobuf:"bytes,65,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CaCert        string                 `protobuf:"bytes,70,opt,name=caCert,proto3" json:"caCert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRegistrationResponse) Reset() {
	*x = NodeRegistrationResponse{}
	mi := &file_nodeward_l1sec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRegistrationResponse) ProtoMessage() {}

func (x *NodeRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l1sec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRegistrationResponse.ProtoReflect.Descriptor instead.
func (*NodeRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l1sec_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRegistrationResponse) GetNid() string {
	if x != nil {
		return x.Nid
	}
	return ""
}

func (x *NodeRegistrationResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *NodeRegistrationResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *NodeRegistrationResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

type ServerRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MachineId     string                 `protobuf:"bytes,25,opt,name=machineId,proto3" json:"machineId,omitempty"`
	Aid           string                 `protobuf:"bytes,30,opt,name=aid,proto3" json:"aid,omitempty"`
	Token         string                 `protobuf:"bytes,35,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRegistrationRequest) Reset() {
	*x = ServerRegistrationRequest{}
	mi := &file_nodeward_l1sec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegistrationRequest) ProtoMessage() {}

func (x *ServerRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l1sec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegistrationRequest.ProtoReflect.Descriptor instead.
func (*ServerRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l1sec_proto_rawDescGZIP(), []int{2}
}

func (x *ServerRegistrationRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *ServerRegistrationRequest) GetAid() string {
	if x != nil {
		return x.Aid
	}
	return ""
}

func (x *ServerRegistrationRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ServerRegistrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,50,opt,name=sid,proto3" json:"sid,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,60,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string                 `protobuf:"bytes,65,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CaCert        string                 `protobuf:"bytes,70,opt,name=caCert,proto3" json:"caCert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRegistrationResponse) Reset() {
	*x = ServerRegistrationResponse{}
	mi := &file_nodeward_l1sec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegistrationResponse) ProtoMessage() {}

func (x *ServerRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l1sec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegistrationResponse.ProtoReflect.Descriptor instead.
func (*ServerRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l1sec_proto_rawDescGZIP(), []int{3}
}

func (x *ServerRegistrationResponse) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *ServerRegistrationResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *ServerRegistrationResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *ServerRegistrationResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

var File_nodeward_l1sec_proto protoreflect.FileDescriptor

const file_nodeward_l1sec_proto_rawDesc = "" +
	"\n" +
	"\x14nodeward_l1sec.proto\x12\x1arunos.nodeward.proto.l1sec\"o\n" +
	"\x17NodeRegistrationRequest\x12\x1c\n" +
	"\tmachineId\x18\x19 \x01(\tR\tmachineId\x12\x10\n" +
	"\x03aid\x18\x1e \x01(\tR\x03aid\x12\x14\n" +
	"\x05token\x18# \x01(\tR\x05token\x12\x0e\n" +
	"\x02os\x18( \x01(\tR\x02os\"\x82\x01\n" +
	"\x18NodeRegistrationResponse\x12\x10\n" +
	"\x03nid\x182 \x01(\tR\x03nid\x12\x1e\n" +
	"\n" +
	"privateKey\x18< \x01(\tR\n" +
	"privateKey\x12\x1c\n" +
	"\tpublicKey\x18A \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06caCert\x18F \x01(\tR\x06caCert\"a\n" +
	"\x19ServerRegistrationRequest\x12\x1c\n" +
	"\tmachineId\x18\x19 \x01(\tR\tmachineId\x12\x10\n" +
	"\x03aid\x18\x1e \x01(\tR\x03aid\x12\x14\n" +
	"\x05token\x18# \x01(\tR\x05token\"\x84\x01\n" +
	"\x1aServerRegistrationResponse\x12\x10\n" +
	"\x03sid\x182 \x01(\tR\x03sid\x12\x1e\n" +
	"\n" +
	"privateKey\x18< \x01(\tR\n" +
	"privateKey\x12\x1c\n" +
	"\tpublicKey\x18A \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06caCert\x18F \x01(\tR\x06caCert2\x82\x02\n" +
	"\bNodeward\x12u\n" +
	"\bRegister\x123.runos.nodeward.proto.l1sec.NodeRegistrationRequest\x1a4.runos.nodeward.proto.l1sec.NodeRegistrationResponse\x12\x7f\n" +
	"\x0eServerRegister\x125.runos.nodeward.proto.l1sec.ServerRegistrationRequest\x1a6.runos.nodeward.proto.l1sec.ServerRegistrationResponseB!Z\x1fnodeward.runos.com/protos/l1secb\x06proto3"

var (
	file_nodeward_l1sec_proto_rawDescOnce sync.Once
	file_nodeward_l1sec_proto_rawDescData []byte
)

func file_nodeward_l1sec_proto_rawDescGZIP() []byte {
	file_nodeward_l1sec_proto_rawDescOnce.Do(func() {
		file_nodeward_l1sec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeward_l1sec_proto_rawDesc), len(file_nodeward_l1sec_proto_rawDesc)))
	})
	return file_nodeward_l1sec_proto_rawDescData
}

var file_nodeward_l1sec_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_nodeward_l1sec_proto_goTypes = []any{
	(*NodeRegistrationRequest)(nil),    // 0: runos.nodeward.proto.l1sec.NodeRegistrationRequest
	(*NodeRegistrationResponse)(nil),   // 1: runos.nodeward.proto.l1sec.NodeRegistrationResponse
	(*ServerRegistrationRequest)(nil),  // 2: runos.nodeward.proto.l1sec.ServerRegistrationRequest
	(*ServerRegistrationResponse)(nil), // 3: runos.nodeward.proto.l1sec.ServerRegistrationResponse
}
var file_nodeward_l1sec_proto_depIdxs = []int32{
	0, // 0: runos.nodeward.proto.l1sec.Nodeward.Register:input_type -> runos.nodeward.proto.l1sec.NodeRegistrationRequest
	2, // 1: runos.nodeward.proto.l1sec.Nodeward.ServerRegister:input_type -> runos.nodeward.proto.l1sec.ServerRegistrationRequest
	1, // 2: runos.nodeward.proto.l1sec.Nodeward.Register:output_type -> runos.nodeward.proto.l1sec.NodeRegistrationResponse
	3, // 3: runos.nodeward.proto.l1sec.Nodeward.ServerRegister:output_type -> runos.nodeward.proto.l1sec.ServerRegistrationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodeward_l1sec_proto_init() }
func file_nodeward_l1sec_proto_init() {
	if File_nodeward_l1sec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeward_l1sec_proto_rawDesc), len(file_nodeward_l1sec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeward_l1sec_proto_goTypes,
		DependencyIndexes: file_nodeward_l1sec_proto_depIdxs,
		MessageInfos:      file_nodeward_l1sec_proto_msgTypes,
	}.Build()
	File_nodeward_l1sec_proto = out.File
	file_nodeward_l1sec_proto_goTypes = nil
	file_nodeward_l1sec_proto_depIdxs = nil
}
