// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: nodeward_l2sec.proto

package l2sec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetInstallVpnCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallVpnCommandsRequest) Reset() {
	*x = GetInstallVpnCommandsRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallVpnCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallVpnCommandsRequest) ProtoMessage() {}

func (x *GetInstallVpnCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallVpnCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetInstallVpnCommandsRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{0}
}

type GetInstallCommandsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	JsonB64FileList string                 `protobuf:"bytes,5,opt,name=jsonB64FileList,proto3" json:"jsonB64FileList,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetInstallCommandsRequest) Reset() {
	*x = GetInstallCommandsRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallCommandsRequest) ProtoMessage() {}

func (x *GetInstallCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallCommandsRequest.ProtoReflect.Descriptor instead.
func (*GetInstallCommandsRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstallCommandsRequest) GetJsonB64FileList() string {
	if x != nil {
		return x.JsonB64FileList
	}
	return ""
}

type GetNodeRegistrationTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRegistrationTokenRequest) Reset() {
	*x = GetNodeRegistrationTokenRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRegistrationTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRegistrationTokenRequest) ProtoMessage() {}

func (x *GetNodeRegistrationTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRegistrationTokenRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRegistrationTokenRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{2}
}

type GetNodeRegistrationTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRegistrationTokenResponse) Reset() {
	*x = GetNodeRegistrationTokenResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRegistrationTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRegistrationTokenResponse) ProtoMessage() {}

func (x *GetNodeRegistrationTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRegistrationTokenResponse.ProtoReflect.Descriptor instead.
func (*GetNodeRegistrationTokenResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeRegistrationTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type InstallCommandList struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Commands      []*InstallCommandList_InstallCommand `protobuf:"bytes,5,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallCommandList) Reset() {
	*x = InstallCommandList{}
	mi := &file_nodeward_l2sec_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCommandList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCommandList) ProtoMessage() {}

func (x *InstallCommandList) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCommandList.ProtoReflect.Descriptor instead.
func (*InstallCommandList) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{4}
}

func (x *InstallCommandList) GetCommands() []*InstallCommandList_InstallCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type VpnPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PubKey        string                 `protobuf:"bytes,10,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	EndpointIp    string                 `protobuf:"bytes,15,opt,name=endpointIp,proto3" json:"endpointIp,omitempty"`
	Ip            string                 `protobuf:"bytes,20,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VpnPeer) Reset() {
	*x = VpnPeer{}
	mi := &file_nodeward_l2sec_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VpnPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VpnPeer) ProtoMessage() {}

func (x *VpnPeer) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VpnPeer.ProtoReflect.Descriptor instead.
func (*VpnPeer) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{5}
}

func (x *VpnPeer) GetPubKey() string {
	if x != nil {
		return x.PubKey
	}
	return ""
}

func (x *VpnPeer) GetEndpointIp() string {
	if x != nil {
		return x.EndpointIp
	}
	return ""
}

func (x *VpnPeer) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type ManualSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodePeer      *VpnPeer               `protobuf:"bytes,10,opt,name=nodePeer,proto3" json:"nodePeer,omitempty"`
	NodeIsReady   bool                   `protobuf:"varint,25,opt,name=nodeIsReady,proto3" json:"nodeIsReady,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualSyncRequest) Reset() {
	*x = ManualSyncRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualSyncRequest) ProtoMessage() {}

func (x *ManualSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualSyncRequest.ProtoReflect.Descriptor instead.
func (*ManualSyncRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{6}
}

func (x *ManualSyncRequest) GetNodePeer() *VpnPeer {
	if x != nil {
		return x.NodePeer
	}
	return nil
}

func (x *ManualSyncRequest) GetNodeIsReady() bool {
	if x != nil {
		return x.NodeIsReady
	}
	return false
}

type ManualSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*VpnPeer             `protobuf:"bytes,5,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManualSyncResponse) Reset() {
	*x = ManualSyncResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManualSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManualSyncResponse) ProtoMessage() {}

func (x *ManualSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManualSyncResponse.ProtoReflect.Descriptor instead.
func (*ManualSyncResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{7}
}

func (x *ManualSyncResponse) GetPeers() []*VpnPeer {
	if x != nil {
		return x.Peers
	}
	return nil
}

type FromNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromNode) Reset() {
	*x = FromNode{}
	mi := &file_nodeward_l2sec_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromNode) ProtoMessage() {}

func (x *FromNode) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromNode.ProtoReflect.Descriptor instead.
func (*FromNode) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{8}
}

func (x *FromNode) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *FromNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ToNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToNode) Reset() {
	*x = ToNode{}
	mi := &file_nodeward_l2sec_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToNode) ProtoMessage() {}

func (x *ToNode) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToNode.ProtoReflect.Descriptor instead.
func (*ToNode) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{9}
}

func (x *ToNode) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *ToNode) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type FromClusterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromClusterAgent) Reset() {
	*x = FromClusterAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromClusterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromClusterAgent) ProtoMessage() {}

func (x *FromClusterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromClusterAgent.ProtoReflect.Descriptor instead.
func (*FromClusterAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{10}
}

func (x *FromClusterAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *FromClusterAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FromClusterAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ToClusterAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToClusterAgent) Reset() {
	*x = ToClusterAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToClusterAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToClusterAgent) ProtoMessage() {}

func (x *ToClusterAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToClusterAgent.ProtoReflect.Descriptor instead.
func (*ToClusterAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{11}
}

func (x *ToClusterAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *ToClusterAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToClusterAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type FromNodeAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromNodeAgent) Reset() {
	*x = FromNodeAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromNodeAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromNodeAgent) ProtoMessage() {}

func (x *FromNodeAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromNodeAgent.ProtoReflect.Descriptor instead.
func (*FromNodeAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{12}
}

func (x *FromNodeAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *FromNodeAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FromNodeAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ToNodeAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToNodeAgent) Reset() {
	*x = ToNodeAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToNodeAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToNodeAgent) ProtoMessage() {}

func (x *ToNodeAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToNodeAgent.ProtoReflect.Descriptor instead.
func (*ToNodeAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{13}
}

func (x *ToNodeAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *ToNodeAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToNodeAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type FromServerAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromServerAgent) Reset() {
	*x = FromServerAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromServerAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromServerAgent) ProtoMessage() {}

func (x *FromServerAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromServerAgent.ProtoReflect.Descriptor instead.
func (*FromServerAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{14}
}

func (x *FromServerAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *FromServerAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FromServerAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ToServerAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JsonB64       string                 `protobuf:"bytes,1,opt,name=jsonB64,proto3" json:"jsonB64,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Tag           string                 `protobuf:"bytes,10,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToServerAgent) Reset() {
	*x = ToServerAgent{}
	mi := &file_nodeward_l2sec_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToServerAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToServerAgent) ProtoMessage() {}

func (x *ToServerAgent) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToServerAgent.ProtoReflect.Descriptor instead.
func (*ToServerAgent) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{15}
}

func (x *ToServerAgent) GetJsonB64() string {
	if x != nil {
		return x.JsonB64
	}
	return ""
}

func (x *ToServerAgent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToServerAgent) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetClusterAgentCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterAgentCredentialsRequest) Reset() {
	*x = GetClusterAgentCredentialsRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterAgentCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterAgentCredentialsRequest) ProtoMessage() {}

func (x *GetClusterAgentCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterAgentCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetClusterAgentCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{16}
}

type GetClusterAgentCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,60,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string                 `protobuf:"bytes,65,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CaCert        string                 `protobuf:"bytes,70,opt,name=caCert,proto3" json:"caCert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterAgentCredentialsResponse) Reset() {
	*x = GetClusterAgentCredentialsResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterAgentCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterAgentCredentialsResponse) ProtoMessage() {}

func (x *GetClusterAgentCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterAgentCredentialsResponse.ProtoReflect.Descriptor instead.
func (*GetClusterAgentCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{17}
}

func (x *GetClusterAgentCredentialsResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *GetClusterAgentCredentialsResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetClusterAgentCredentialsResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusResponse) Reset() {
	*x = UpdateStatusResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusResponse) ProtoMessage() {}

func (x *UpdateStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{19}
}

type AddNodelogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Severity      int32                  `protobuf:"varint,10,opt,name=severity,proto3" json:"severity,omitempty"`
	Message       string                 `protobuf:"bytes,15,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodelogRequest) Reset() {
	*x = AddNodelogRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodelogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodelogRequest) ProtoMessage() {}

func (x *AddNodelogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodelogRequest.ProtoReflect.Descriptor instead.
func (*AddNodelogRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{20}
}

func (x *AddNodelogRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddNodelogRequest) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *AddNodelogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddNodelogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNodelogResponse) Reset() {
	*x = AddNodelogResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNodelogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNodelogResponse) ProtoMessage() {}

func (x *AddNodelogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNodelogResponse.ProtoReflect.Descriptor instead.
func (*AddNodelogResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{21}
}

type GetControlPlaneNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlPlaneNodesRequest) Reset() {
	*x = GetControlPlaneNodesRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlPlaneNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlPlaneNodesRequest) ProtoMessage() {}

func (x *GetControlPlaneNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlPlaneNodesRequest.ProtoReflect.Descriptor instead.
func (*GetControlPlaneNodesRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{22}
}

type GetControlPlaneNodesResponse struct {
	state             protoimpl.MessageState                           `protogen:"open.v1"`
	ControlPlaneNodes []*GetControlPlaneNodesResponse_ControlPlaneNode `protobuf:"bytes,5,rep,name=ControlPlaneNodes,proto3" json:"ControlPlaneNodes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetControlPlaneNodesResponse) Reset() {
	*x = GetControlPlaneNodesResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlPlaneNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlPlaneNodesResponse) ProtoMessage() {}

func (x *GetControlPlaneNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlPlaneNodesResponse.ProtoReflect.Descriptor instead.
func (*GetControlPlaneNodesResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{23}
}

func (x *GetControlPlaneNodesResponse) GetControlPlaneNodes() []*GetControlPlaneNodesResponse_ControlPlaneNode {
	if x != nil {
		return x.ControlPlaneNodes
	}
	return nil
}

type UpdateNodeInstallationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepCompleted int32                  `protobuf:"varint,10,opt,name=stepCompleted,proto3" json:"stepCompleted,omitempty"`
	ErrorAtStep   int32                  `protobuf:"varint,15,opt,name=errorAtStep,proto3" json:"errorAtStep,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,20,opt,name=errorMessage,proto3" json:"errorMessage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeInstallationStatusRequest) Reset() {
	*x = UpdateNodeInstallationStatusRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeInstallationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeInstallationStatusRequest) ProtoMessage() {}

func (x *UpdateNodeInstallationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeInstallationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateNodeInstallationStatusRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateNodeInstallationStatusRequest) GetStepCompleted() int32 {
	if x != nil {
		return x.StepCompleted
	}
	return 0
}

func (x *UpdateNodeInstallationStatusRequest) GetErrorAtStep() int32 {
	if x != nil {
		return x.ErrorAtStep
	}
	return 0
}

func (x *UpdateNodeInstallationStatusRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UpdateNodeInstallationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNodeInstallationStatusResponse) Reset() {
	*x = UpdateNodeInstallationStatusResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNodeInstallationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNodeInstallationStatusResponse) ProtoMessage() {}

func (x *UpdateNodeInstallationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNodeInstallationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateNodeInstallationStatusResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{25}
}

type RegenerateCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateCertificateRequest) Reset() {
	*x = RegenerateCertificateRequest{}
	mi := &file_nodeward_l2sec_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateCertificateRequest) ProtoMessage() {}

func (x *RegenerateCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateCertificateRequest.ProtoReflect.Descriptor instead.
func (*RegenerateCertificateRequest) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{26}
}

type RegenerateCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateKey    string                 `protobuf:"bytes,5,opt,name=privateKey,proto3" json:"privateKey,omitempty"`
	PublicKey     string                 `protobuf:"bytes,10,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	CaCert        string                 `protobuf:"bytes,15,opt,name=caCert,proto3" json:"caCert,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegenerateCertificateResponse) Reset() {
	*x = RegenerateCertificateResponse{}
	mi := &file_nodeward_l2sec_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegenerateCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegenerateCertificateResponse) ProtoMessage() {}

func (x *RegenerateCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegenerateCertificateResponse.ProtoReflect.Descriptor instead.
func (*RegenerateCertificateResponse) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{27}
}

func (x *RegenerateCertificateResponse) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *RegenerateCertificateResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *RegenerateCertificateResponse) GetCaCert() string {
	if x != nil {
		return x.CaCert
	}
	return ""
}

type InstallCommandList_InstallCommand struct {
	state                            protoimpl.MessageState `protogen:"open.v1"`
	CommandId                        int32                  `protobuf:"varint,5,opt,name=commandId,proto3" json:"commandId,omitempty"`
	Command                          string                 `protobuf:"bytes,10,opt,name=command,proto3" json:"command,omitempty"`
	AfterCommandId                   int32                  `protobuf:"varint,15,opt,name=afterCommandId,proto3" json:"afterCommandId,omitempty"`
	AfterCommandIdResultDoesNotMatch string                 `protobuf:"bytes,20,opt,name=afterCommandIdResultDoesNotMatch,proto3" json:"afterCommandIdResultDoesNotMatch,omitempty"`
	AfterCommandIdResultMatches      string                 `protobuf:"bytes,25,opt,name=afterCommandIdResultMatches,proto3" json:"afterCommandIdResultMatches,omitempty"`
	IgnoreFailure                    bool                   `protobuf:"varint,30,opt,name=ignoreFailure,proto3" json:"ignoreFailure,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *InstallCommandList_InstallCommand) Reset() {
	*x = InstallCommandList_InstallCommand{}
	mi := &file_nodeward_l2sec_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallCommandList_InstallCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallCommandList_InstallCommand) ProtoMessage() {}

func (x *InstallCommandList_InstallCommand) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallCommandList_InstallCommand.ProtoReflect.Descriptor instead.
func (*InstallCommandList_InstallCommand) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{4, 0}
}

func (x *InstallCommandList_InstallCommand) GetCommandId() int32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *InstallCommandList_InstallCommand) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *InstallCommandList_InstallCommand) GetAfterCommandId() int32 {
	if x != nil {
		return x.AfterCommandId
	}
	return 0
}

func (x *InstallCommandList_InstallCommand) GetAfterCommandIdResultDoesNotMatch() string {
	if x != nil {
		return x.AfterCommandIdResultDoesNotMatch
	}
	return ""
}

func (x *InstallCommandList_InstallCommand) GetAfterCommandIdResultMatches() string {
	if x != nil {
		return x.AfterCommandIdResultMatches
	}
	return ""
}

func (x *InstallCommandList_InstallCommand) GetIgnoreFailure() bool {
	if x != nil {
		return x.IgnoreFailure
	}
	return false
}

type GetControlPlaneNodesResponse_ControlPlaneNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VpnIp         string                 `protobuf:"bytes,1,opt,name=vpnIp,proto3" json:"vpnIp,omitempty"`
	KubeEndpoint  string                 `protobuf:"bytes,5,opt,name=kubeEndpoint,proto3" json:"kubeEndpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetControlPlaneNodesResponse_ControlPlaneNode) Reset() {
	*x = GetControlPlaneNodesResponse_ControlPlaneNode{}
	mi := &file_nodeward_l2sec_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetControlPlaneNodesResponse_ControlPlaneNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetControlPlaneNodesResponse_ControlPlaneNode) ProtoMessage() {}

func (x *GetControlPlaneNodesResponse_ControlPlaneNode) ProtoReflect() protoreflect.Message {
	mi := &file_nodeward_l2sec_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetControlPlaneNodesResponse_ControlPlaneNode.ProtoReflect.Descriptor instead.
func (*GetControlPlaneNodesResponse_ControlPlaneNode) Descriptor() ([]byte, []int) {
	return file_nodeward_l2sec_proto_rawDescGZIP(), []int{23, 0}
}

func (x *GetControlPlaneNodesResponse_ControlPlaneNode) GetVpnIp() string {
	if x != nil {
		return x.VpnIp
	}
	return ""
}

func (x *GetControlPlaneNodesResponse_ControlPlaneNode) GetKubeEndpoint() string {
	if x != nil {
		return x.KubeEndpoint
	}
	return ""
}

var File_nodeward_l2sec_proto protoreflect.FileDescriptor

const file_nodeward_l2sec_proto_rawDesc = "" +
	"\n" +
	"\x14nodeward_l2sec.proto\x12\x1arunos.nodeward.proto.l2sec\"\x1e\n" +
	"\x1cGetInstallVpnCommandsRequest\"E\n" +
	"\x19GetInstallCommandsRequest\x12(\n" +
	"\x0fjsonB64FileList\x18\x05 \x01(\tR\x0fjsonB64FileList\"!\n" +
	"\x1fGetNodeRegistrationTokenRequest\"8\n" +
	" GetNodeRegistrationTokenResponse\x12\x14\n" +
	"\x05token\x18\x05 \x01(\tR\x05token\"\x96\x03\n" +
	"\x12InstallCommandList\x12Y\n" +
	"\bcommands\x18\x05 \x03(\v2=.runos.nodeward.proto.l2sec.InstallCommandList.InstallCommandR\bcommands\x1a\xa4\x02\n" +
	"\x0eInstallCommand\x12\x1c\n" +
	"\tcommandId\x18\x05 \x01(\x05R\tcommandId\x12\x18\n" +
	"\acommand\x18\n" +
	" \x01(\tR\acommand\x12&\n" +
	"\x0eafterCommandId\x18\x0f \x01(\x05R\x0eafterCommandId\x12J\n" +
	" afterCommandIdResultDoesNotMatch\x18\x14 \x01(\tR afterCommandIdResultDoesNotMatch\x12@\n" +
	"\x1bafterCommandIdResultMatches\x18\x19 \x01(\tR\x1bafterCommandIdResultMatches\x12$\n" +
	"\rignoreFailure\x18\x1e \x01(\bR\rignoreFailure\"Q\n" +
	"\aVpnPeer\x12\x16\n" +
	"\x06pubKey\x18\n" +
	" \x01(\tR\x06pubKey\x12\x1e\n" +
	"\n" +
	"endpointIp\x18\x0f \x01(\tR\n" +
	"endpointIp\x12\x0e\n" +
	"\x02ip\x18\x14 \x01(\tR\x02ip\"v\n" +
	"\x11ManualSyncRequest\x12?\n" +
	"\bnodePeer\x18\n" +
	" \x01(\v2#.runos.nodeward.proto.l2sec.VpnPeerR\bnodePeer\x12 \n" +
	"\vnodeIsReady\x18\x19 \x01(\bR\vnodeIsReady\"O\n" +
	"\x12ManualSyncResponse\x129\n" +
	"\x05peers\x18\x05 \x03(\v2#.runos.nodeward.proto.l2sec.VpnPeerR\x05peers\"8\n" +
	"\bFromNode\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"6\n" +
	"\x06ToNode\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"R\n" +
	"\x10FromClusterAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"P\n" +
	"\x0eToClusterAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"O\n" +
	"\rFromNodeAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"M\n" +
	"\vToNodeAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"Q\n" +
	"\x0fFromServerAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"O\n" +
	"\rToServerAgent\x12\x18\n" +
	"\ajsonB64\x18\x01 \x01(\tR\ajsonB64\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x10\n" +
	"\x03tag\x18\n" +
	" \x01(\tR\x03tag\"#\n" +
	"!GetClusterAgentCredentialsRequest\"z\n" +
	"\"GetClusterAgentCredentialsResponse\x12\x1e\n" +
	"\n" +
	"privateKey\x18< \x01(\tR\n" +
	"privateKey\x12\x1c\n" +
	"\tpublicKey\x18A \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06caCert\x18F \x01(\tR\x06caCert\"-\n" +
	"\x13UpdateStatusRequest\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x16\n" +
	"\x14UpdateStatusResponse\"]\n" +
	"\x11AddNodelogRequest\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bseverity\x18\n" +
	" \x01(\x05R\bseverity\x12\x18\n" +
	"\amessage\x18\x0f \x01(\tR\amessage\"\x14\n" +
	"\x12AddNodelogResponse\"\x1d\n" +
	"\x1bGetControlPlaneNodesRequest\"\xe5\x01\n" +
	"\x1cGetControlPlaneNodesResponse\x12w\n" +
	"\x11ControlPlaneNodes\x18\x05 \x03(\v2I.runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse.ControlPlaneNodeR\x11ControlPlaneNodes\x1aL\n" +
	"\x10ControlPlaneNode\x12\x14\n" +
	"\x05vpnIp\x18\x01 \x01(\tR\x05vpnIp\x12\"\n" +
	"\fkubeEndpoint\x18\x05 \x01(\tR\fkubeEndpoint\"\x91\x01\n" +
	"#UpdateNodeInstallationStatusRequest\x12$\n" +
	"\rstepCompleted\x18\n" +
	" \x01(\x05R\rstepCompleted\x12 \n" +
	"\verrorAtStep\x18\x0f \x01(\x05R\verrorAtStep\x12\"\n" +
	"\ferrorMessage\x18\x14 \x01(\tR\ferrorMessage\"&\n" +
	"$UpdateNodeInstallationStatusResponse\"\x1e\n" +
	"\x1cRegenerateCertificateRequest\"u\n" +
	"\x1dRegenerateCertificateResponse\x12\x1e\n" +
	"\n" +
	"privateKey\x18\x05 \x01(\tR\n" +
	"privateKey\x12\x1c\n" +
	"\tpublicKey\x18\n" +
	" \x01(\tR\tpublicKey\x12\x16\n" +
	"\x06caCert\x18\x0f \x01(\tR\x06caCert2\xfa\r\n" +
	"\bNodeward\x12\x81\x01\n" +
	"\x15GetInstallVpnCommands\x128.runos.nodeward.proto.l2sec.GetInstallVpnCommandsRequest\x1a..runos.nodeward.proto.l2sec.InstallCommandList\x12{\n" +
	"\x12GetInstallCommands\x125.runos.nodeward.proto.l2sec.GetInstallCommandsRequest\x1a..runos.nodeward.proto.l2sec.InstallCommandList\x12k\n" +
	"\n" +
	"ManualSync\x12-.runos.nodeward.proto.l2sec.ManualSyncRequest\x1a..runos.nodeward.proto.l2sec.ManualSyncResponse\x12\x95\x01\n" +
	"\x18GetNodeRegistrationToken\x12;.runos.nodeward.proto.l2sec.GetNodeRegistrationTokenRequest\x1a<.runos.nodeward.proto.l2sec.GetNodeRegistrationTokenResponse\x12[\n" +
	"\vCommunicate\x12$.runos.nodeward.proto.l2sec.FromNode\x1a\".runos.nodeward.proto.l2sec.ToNode(\x010\x01\x12r\n" +
	"\x12ClusterAgentStream\x12,.runos.nodeward.proto.l2sec.FromClusterAgent\x1a*.runos.nodeward.proto.l2sec.ToClusterAgent(\x010\x01\x12i\n" +
	"\x0fNodeAgentStream\x12).runos.nodeward.proto.l2sec.FromNodeAgent\x1a'.runos.nodeward.proto.l2sec.ToNodeAgent(\x010\x01\x12o\n" +
	"\x11ServerAgentStream\x12+.runos.nodeward.proto.l2sec.FromServerAgent\x1a).runos.nodeward.proto.l2sec.ToServerAgent(\x010\x01\x12\x9b\x01\n" +
	"\x1aGetClusterAgentCredentials\x12=.runos.nodeward.proto.l2sec.GetClusterAgentCredentialsRequest\x1a>.runos.nodeward.proto.l2sec.GetClusterAgentCredentialsResponse\x12q\n" +
	"\fUpdateStatus\x12/.runos.nodeward.proto.l2sec.UpdateStatusRequest\x1a0.runos.nodeward.proto.l2sec.UpdateStatusResponse\x12k\n" +
	"\n" +
	"AddNodelog\x12-.runos.nodeward.proto.l2sec.AddNodelogRequest\x1a..runos.nodeward.proto.l2sec.AddNodelogResponse\x12\x89\x01\n" +
	"\x14GetControlPlaneNodes\x127.runos.nodeward.proto.l2sec.GetControlPlaneNodesRequest\x1a8.runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse\x12\xa1\x01\n" +
	"\x1cUpdateNodeInstallationStatus\x12?.runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusRequest\x1a@.runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusResponse\x12\x8c\x01\n" +
	"\x15RegenerateCertificate\x128.runos.nodeward.proto.l2sec.RegenerateCertificateRequest\x1a9.runos.nodeward.proto.l2sec.RegenerateCertificateResponseB!Z\x1fnodeward.runos.com/protos/l2secb\x06proto3"

var (
	file_nodeward_l2sec_proto_rawDescOnce sync.Once
	file_nodeward_l2sec_proto_rawDescData []byte
)

func file_nodeward_l2sec_proto_rawDescGZIP() []byte {
	file_nodeward_l2sec_proto_rawDescOnce.Do(func() {
		file_nodeward_l2sec_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nodeward_l2sec_proto_rawDesc), len(file_nodeward_l2sec_proto_rawDesc)))
	})
	return file_nodeward_l2sec_proto_rawDescData
}

var file_nodeward_l2sec_proto_msgTypes = make([]protoimpl.MessageInfo, 30)
var file_nodeward_l2sec_proto_goTypes = []any{
	(*GetInstallVpnCommandsRequest)(nil),                  // 0: runos.nodeward.proto.l2sec.GetInstallVpnCommandsRequest
	(*GetInstallCommandsRequest)(nil),                     // 1: runos.nodeward.proto.l2sec.GetInstallCommandsRequest
	(*GetNodeRegistrationTokenRequest)(nil),               // 2: runos.nodeward.proto.l2sec.GetNodeRegistrationTokenRequest
	(*GetNodeRegistrationTokenResponse)(nil),              // 3: runos.nodeward.proto.l2sec.GetNodeRegistrationTokenResponse
	(*InstallCommandList)(nil),                            // 4: runos.nodeward.proto.l2sec.InstallCommandList
	(*VpnPeer)(nil),                                       // 5: runos.nodeward.proto.l2sec.VpnPeer
	(*ManualSyncRequest)(nil),                             // 6: runos.nodeward.proto.l2sec.ManualSyncRequest
	(*ManualSyncResponse)(nil),                            // 7: runos.nodeward.proto.l2sec.ManualSyncResponse
	(*FromNode)(nil),                                      // 8: runos.nodeward.proto.l2sec.FromNode
	(*ToNode)(nil),                                        // 9: runos.nodeward.proto.l2sec.ToNode
	(*FromClusterAgent)(nil),                              // 10: runos.nodeward.proto.l2sec.FromClusterAgent
	(*ToClusterAgent)(nil),                                // 11: runos.nodeward.proto.l2sec.ToClusterAgent
	(*FromNodeAgent)(nil),                                 // 12: runos.nodeward.proto.l2sec.FromNodeAgent
	(*ToNodeAgent)(nil),                                   // 13: runos.nodeward.proto.l2sec.ToNodeAgent
	(*FromServerAgent)(nil),                               // 14: runos.nodeward.proto.l2sec.FromServerAgent
	(*ToServerAgent)(nil),                                 // 15: runos.nodeward.proto.l2sec.ToServerAgent
	(*GetClusterAgentCredentialsRequest)(nil),             // 16: runos.nodeward.proto.l2sec.GetClusterAgentCredentialsRequest
	(*GetClusterAgentCredentialsResponse)(nil),            // 17: runos.nodeward.proto.l2sec.GetClusterAgentCredentialsResponse
	(*UpdateStatusRequest)(nil),                           // 18: runos.nodeward.proto.l2sec.UpdateStatusRequest
	(*UpdateStatusResponse)(nil),                          // 19: runos.nodeward.proto.l2sec.UpdateStatusResponse
	(*AddNodelogRequest)(nil),                             // 20: runos.nodeward.proto.l2sec.AddNodelogRequest
	(*AddNodelogResponse)(nil),                            // 21: runos.nodeward.proto.l2sec.AddNodelogResponse
	(*GetControlPlaneNodesRequest)(nil),                   // 22: runos.nodeward.proto.l2sec.GetControlPlaneNodesRequest
	(*GetControlPlaneNodesResponse)(nil),                  // 23: runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse
	(*UpdateNodeInstallationStatusRequest)(nil),           // 24: runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusRequest
	(*UpdateNodeInstallationStatusResponse)(nil),          // 25: runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusResponse
	(*RegenerateCertificateRequest)(nil),                  // 26: runos.nodeward.proto.l2sec.RegenerateCertificateRequest
	(*RegenerateCertificateResponse)(nil),                 // 27: runos.nodeward.proto.l2sec.RegenerateCertificateResponse
	(*InstallCommandList_InstallCommand)(nil),             // 28: runos.nodeward.proto.l2sec.InstallCommandList.InstallCommand
	(*GetControlPlaneNodesResponse_ControlPlaneNode)(nil), // 29: runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse.ControlPlaneNode
}
var file_nodeward_l2sec_proto_depIdxs = []int32{
	28, // 0: runos.nodeward.proto.l2sec.InstallCommandList.commands:type_name -> runos.nodeward.proto.l2sec.InstallCommandList.InstallCommand
	5,  // 1: runos.nodeward.proto.l2sec.ManualSyncRequest.nodePeer:type_name -> runos.nodeward.proto.l2sec.VpnPeer
	5,  // 2: runos.nodeward.proto.l2sec.ManualSyncResponse.peers:type_name -> runos.nodeward.proto.l2sec.VpnPeer
	29, // 3: runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse.ControlPlaneNodes:type_name -> runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse.ControlPlaneNode
	0,  // 4: runos.nodeward.proto.l2sec.Nodeward.GetInstallVpnCommands:input_type -> runos.nodeward.proto.l2sec.GetInstallVpnCommandsRequest
	1,  // 5: runos.nodeward.proto.l2sec.Nodeward.GetInstallCommands:input_type -> runos.nodeward.proto.l2sec.GetInstallCommandsRequest
	6,  // 6: runos.nodeward.proto.l2sec.Nodeward.ManualSync:input_type -> runos.nodeward.proto.l2sec.ManualSyncRequest
	2,  // 7: runos.nodeward.proto.l2sec.Nodeward.GetNodeRegistrationToken:input_type -> runos.nodeward.proto.l2sec.GetNodeRegistrationTokenRequest
	8,  // 8: runos.nodeward.proto.l2sec.Nodeward.Communicate:input_type -> runos.nodeward.proto.l2sec.FromNode
	10, // 9: runos.nodeward.proto.l2sec.Nodeward.ClusterAgentStream:input_type -> runos.nodeward.proto.l2sec.FromClusterAgent
	12, // 10: runos.nodeward.proto.l2sec.Nodeward.NodeAgentStream:input_type -> runos.nodeward.proto.l2sec.FromNodeAgent
	14, // 11: runos.nodeward.proto.l2sec.Nodeward.ServerAgentStream:input_type -> runos.nodeward.proto.l2sec.FromServerAgent
	16, // 12: runos.nodeward.proto.l2sec.Nodeward.GetClusterAgentCredentials:input_type -> runos.nodeward.proto.l2sec.GetClusterAgentCredentialsRequest
	18, // 13: runos.nodeward.proto.l2sec.Nodeward.UpdateStatus:input_type -> runos.nodeward.proto.l2sec.UpdateStatusRequest
	20, // 14: runos.nodeward.proto.l2sec.Nodeward.AddNodelog:input_type -> runos.nodeward.proto.l2sec.AddNodelogRequest
	22, // 15: runos.nodeward.proto.l2sec.Nodeward.GetControlPlaneNodes:input_type -> runos.nodeward.proto.l2sec.GetControlPlaneNodesRequest
	24, // 16: runos.nodeward.proto.l2sec.Nodeward.UpdateNodeInstallationStatus:input_type -> runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusRequest
	26, // 17: runos.nodeward.proto.l2sec.Nodeward.RegenerateCertificate:input_type -> runos.nodeward.proto.l2sec.RegenerateCertificateRequest
	4,  // 18: runos.nodeward.proto.l2sec.Nodeward.GetInstallVpnCommands:output_type -> runos.nodeward.proto.l2sec.InstallCommandList
	4,  // 19: runos.nodeward.proto.l2sec.Nodeward.GetInstallCommands:output_type -> runos.nodeward.proto.l2sec.InstallCommandList
	7,  // 20: runos.nodeward.proto.l2sec.Nodeward.ManualSync:output_type -> runos.nodeward.proto.l2sec.ManualSyncResponse
	3,  // 21: runos.nodeward.proto.l2sec.Nodeward.GetNodeRegistrationToken:output_type -> runos.nodeward.proto.l2sec.GetNodeRegistrationTokenResponse
	9,  // 22: runos.nodeward.proto.l2sec.Nodeward.Communicate:output_type -> runos.nodeward.proto.l2sec.ToNode
	11, // 23: runos.nodeward.proto.l2sec.Nodeward.ClusterAgentStream:output_type -> runos.nodeward.proto.l2sec.ToClusterAgent
	13, // 24: runos.nodeward.proto.l2sec.Nodeward.NodeAgentStream:output_type -> runos.nodeward.proto.l2sec.ToNodeAgent
	15, // 25: runos.nodeward.proto.l2sec.Nodeward.ServerAgentStream:output_type -> runos.nodeward.proto.l2sec.ToServerAgent
	17, // 26: runos.nodeward.proto.l2sec.Nodeward.GetClusterAgentCredentials:output_type -> runos.nodeward.proto.l2sec.GetClusterAgentCredentialsResponse
	19, // 27: runos.nodeward.proto.l2sec.Nodeward.UpdateStatus:output_type -> runos.nodeward.proto.l2sec.UpdateStatusResponse
	21, // 28: runos.nodeward.proto.l2sec.Nodeward.AddNodelog:output_type -> runos.nodeward.proto.l2sec.AddNodelogResponse
	23, // 29: runos.nodeward.proto.l2sec.Nodeward.GetControlPlaneNodes:output_type -> runos.nodeward.proto.l2sec.GetControlPlaneNodesResponse
	25, // 30: runos.nodeward.proto.l2sec.Nodeward.UpdateNodeInstallationStatus:output_type -> runos.nodeward.proto.l2sec.UpdateNodeInstallationStatusResponse
	27, // 31: runos.nodeward.proto.l2sec.Nodeward.RegenerateCertificate:output_type -> runos.nodeward.proto.l2sec.RegenerateCertificateResponse
	18, // [18:32] is the sub-list for method output_type
	4,  // [4:18] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_nodeward_l2sec_proto_init() }
func file_nodeward_l2sec_proto_init() {
	if File_nodeward_l2sec_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nodeward_l2sec_proto_rawDesc), len(file_nodeward_l2sec_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   30,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeward_l2sec_proto_goTypes,
		DependencyIndexes: file_nodeward_l2sec_proto_depIdxs,
		MessageInfos:      file_nodeward_l2sec_proto_msgTypes,
	}.Build()
	File_nodeward_l2sec_proto = out.File
	file_nodeward_l2sec_proto_goTypes = nil
	file_nodeward_l2sec_proto_depIdxs = nil
}
