// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: nodeward_l2sec.proto

package l2sec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Nodeward_GetInstallVpnCommands_FullMethodName        = "/runos.nodeward.proto.l2sec.Nodeward/GetInstallVpnCommands"
	Nodeward_GetInstallCommands_FullMethodName           = "/runos.nodeward.proto.l2sec.Nodeward/GetInstallCommands"
	Nodeward_ManualSync_FullMethodName                   = "/runos.nodeward.proto.l2sec.Nodeward/ManualSync"
	Nodeward_GetNodeRegistrationToken_FullMethodName     = "/runos.nodeward.proto.l2sec.Nodeward/GetNodeRegistrationToken"
	Nodeward_Communicate_FullMethodName                  = "/runos.nodeward.proto.l2sec.Nodeward/Communicate"
	Nodeward_ClusterAgentStream_FullMethodName           = "/runos.nodeward.proto.l2sec.Nodeward/ClusterAgentStream"
	Nodeward_NodeAgentStream_FullMethodName              = "/runos.nodeward.proto.l2sec.Nodeward/NodeAgentStream"
	Nodeward_ServerAgentStream_FullMethodName            = "/runos.nodeward.proto.l2sec.Nodeward/ServerAgentStream"
	Nodeward_GetClusterAgentCredentials_FullMethodName   = "/runos.nodeward.proto.l2sec.Nodeward/GetClusterAgentCredentials"
	Nodeward_UpdateStatus_FullMethodName                 = "/runos.nodeward.proto.l2sec.Nodeward/UpdateStatus"
	Nodeward_AddNodelog_FullMethodName                   = "/runos.nodeward.proto.l2sec.Nodeward/AddNodelog"
	Nodeward_GetControlPlaneNodes_FullMethodName         = "/runos.nodeward.proto.l2sec.Nodeward/GetControlPlaneNodes"
	Nodeward_UpdateNodeInstallationStatus_FullMethodName = "/runos.nodeward.proto.l2sec.Nodeward/UpdateNodeInstallationStatus"
	Nodeward_RegenerateCertificate_FullMethodName        = "/runos.nodeward.proto.l2sec.Nodeward/RegenerateCertificate"
)

// NodewardClient is the client API for Nodeward service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodewardClient interface {
	GetInstallVpnCommands(ctx context.Context, in *GetInstallVpnCommandsRequest, opts ...grpc.CallOption) (*InstallCommandList, error)
	GetInstallCommands(ctx context.Context, in *GetInstallCommandsRequest, opts ...grpc.CallOption) (*InstallCommandList, error)
	ManualSync(ctx context.Context, in *ManualSyncRequest, opts ...grpc.CallOption) (*ManualSyncResponse, error)
	GetNodeRegistrationToken(ctx context.Context, in *GetNodeRegistrationTokenRequest, opts ...grpc.CallOption) (*GetNodeRegistrationTokenResponse, error)
	Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromNode, ToNode], error)
	ClusterAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromClusterAgent, ToClusterAgent], error)
	NodeAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromNodeAgent, ToNodeAgent], error)
	ServerAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromServerAgent, ToServerAgent], error)
	GetClusterAgentCredentials(ctx context.Context, in *GetClusterAgentCredentialsRequest, opts ...grpc.CallOption) (*GetClusterAgentCredentialsResponse, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error)
	AddNodelog(ctx context.Context, in *AddNodelogRequest, opts ...grpc.CallOption) (*AddNodelogResponse, error)
	GetControlPlaneNodes(ctx context.Context, in *GetControlPlaneNodesRequest, opts ...grpc.CallOption) (*GetControlPlaneNodesResponse, error)
	UpdateNodeInstallationStatus(ctx context.Context, in *UpdateNodeInstallationStatusRequest, opts ...grpc.CallOption) (*UpdateNodeInstallationStatusResponse, error)
	RegenerateCertificate(ctx context.Context, in *RegenerateCertificateRequest, opts ...grpc.CallOption) (*RegenerateCertificateResponse, error)
}

type nodewardClient struct {
	cc grpc.ClientConnInterface
}

func NewNodewardClient(cc grpc.ClientConnInterface) NodewardClient {
	return &nodewardClient{cc}
}

func (c *nodewardClient) GetInstallVpnCommands(ctx context.Context, in *GetInstallVpnCommandsRequest, opts ...grpc.CallOption) (*InstallCommandList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallCommandList)
	err := c.cc.Invoke(ctx, Nodeward_GetInstallVpnCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) GetInstallCommands(ctx context.Context, in *GetInstallCommandsRequest, opts ...grpc.CallOption) (*InstallCommandList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallCommandList)
	err := c.cc.Invoke(ctx, Nodeward_GetInstallCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) ManualSync(ctx context.Context, in *ManualSyncRequest, opts ...grpc.CallOption) (*ManualSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ManualSyncResponse)
	err := c.cc.Invoke(ctx, Nodeward_ManualSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) GetNodeRegistrationToken(ctx context.Context, in *GetNodeRegistrationTokenRequest, opts ...grpc.CallOption) (*GetNodeRegistrationTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeRegistrationTokenResponse)
	err := c.cc.Invoke(ctx, Nodeward_GetNodeRegistrationToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) Communicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromNode, ToNode], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nodeward_ServiceDesc.Streams[0], Nodeward_Communicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromNode, ToNode]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_CommunicateClient = grpc.BidiStreamingClient[FromNode, ToNode]

func (c *nodewardClient) ClusterAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromClusterAgent, ToClusterAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nodeward_ServiceDesc.Streams[1], Nodeward_ClusterAgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromClusterAgent, ToClusterAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_ClusterAgentStreamClient = grpc.BidiStreamingClient[FromClusterAgent, ToClusterAgent]

func (c *nodewardClient) NodeAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromNodeAgent, ToNodeAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nodeward_ServiceDesc.Streams[2], Nodeward_NodeAgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromNodeAgent, ToNodeAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_NodeAgentStreamClient = grpc.BidiStreamingClient[FromNodeAgent, ToNodeAgent]

func (c *nodewardClient) ServerAgentStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[FromServerAgent, ToServerAgent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Nodeward_ServiceDesc.Streams[3], Nodeward_ServerAgentStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FromServerAgent, ToServerAgent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_ServerAgentStreamClient = grpc.BidiStreamingClient[FromServerAgent, ToServerAgent]

func (c *nodewardClient) GetClusterAgentCredentials(ctx context.Context, in *GetClusterAgentCredentialsRequest, opts ...grpc.CallOption) (*GetClusterAgentCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterAgentCredentialsResponse)
	err := c.cc.Invoke(ctx, Nodeward_GetClusterAgentCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) UpdateStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*UpdateStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStatusResponse)
	err := c.cc.Invoke(ctx, Nodeward_UpdateStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) AddNodelog(ctx context.Context, in *AddNodelogRequest, opts ...grpc.CallOption) (*AddNodelogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNodelogResponse)
	err := c.cc.Invoke(ctx, Nodeward_AddNodelog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) GetControlPlaneNodes(ctx context.Context, in *GetControlPlaneNodesRequest, opts ...grpc.CallOption) (*GetControlPlaneNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetControlPlaneNodesResponse)
	err := c.cc.Invoke(ctx, Nodeward_GetControlPlaneNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) UpdateNodeInstallationStatus(ctx context.Context, in *UpdateNodeInstallationStatusRequest, opts ...grpc.CallOption) (*UpdateNodeInstallationStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeInstallationStatusResponse)
	err := c.cc.Invoke(ctx, Nodeward_UpdateNodeInstallationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodewardClient) RegenerateCertificate(ctx context.Context, in *RegenerateCertificateRequest, opts ...grpc.CallOption) (*RegenerateCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegenerateCertificateResponse)
	err := c.cc.Invoke(ctx, Nodeward_RegenerateCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodewardServer is the server API for Nodeward service.
// All implementations must embed UnimplementedNodewardServer
// for forward compatibility.
type NodewardServer interface {
	GetInstallVpnCommands(context.Context, *GetInstallVpnCommandsRequest) (*InstallCommandList, error)
	GetInstallCommands(context.Context, *GetInstallCommandsRequest) (*InstallCommandList, error)
	ManualSync(context.Context, *ManualSyncRequest) (*ManualSyncResponse, error)
	GetNodeRegistrationToken(context.Context, *GetNodeRegistrationTokenRequest) (*GetNodeRegistrationTokenResponse, error)
	Communicate(grpc.BidiStreamingServer[FromNode, ToNode]) error
	ClusterAgentStream(grpc.BidiStreamingServer[FromClusterAgent, ToClusterAgent]) error
	NodeAgentStream(grpc.BidiStreamingServer[FromNodeAgent, ToNodeAgent]) error
	ServerAgentStream(grpc.BidiStreamingServer[FromServerAgent, ToServerAgent]) error
	GetClusterAgentCredentials(context.Context, *GetClusterAgentCredentialsRequest) (*GetClusterAgentCredentialsResponse, error)
	UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error)
	AddNodelog(context.Context, *AddNodelogRequest) (*AddNodelogResponse, error)
	GetControlPlaneNodes(context.Context, *GetControlPlaneNodesRequest) (*GetControlPlaneNodesResponse, error)
	UpdateNodeInstallationStatus(context.Context, *UpdateNodeInstallationStatusRequest) (*UpdateNodeInstallationStatusResponse, error)
	RegenerateCertificate(context.Context, *RegenerateCertificateRequest) (*RegenerateCertificateResponse, error)
	mustEmbedUnimplementedNodewardServer()
}

// UnimplementedNodewardServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodewardServer struct{}

func (UnimplementedNodewardServer) GetInstallVpnCommands(context.Context, *GetInstallVpnCommandsRequest) (*InstallCommandList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstallVpnCommands not implemented")
}
func (UnimplementedNodewardServer) GetInstallCommands(context.Context, *GetInstallCommandsRequest) (*InstallCommandList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstallCommands not implemented")
}
func (UnimplementedNodewardServer) ManualSync(context.Context, *ManualSyncRequest) (*ManualSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ManualSync not implemented")
}
func (UnimplementedNodewardServer) GetNodeRegistrationToken(context.Context, *GetNodeRegistrationTokenRequest) (*GetNodeRegistrationTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeRegistrationToken not implemented")
}
func (UnimplementedNodewardServer) Communicate(grpc.BidiStreamingServer[FromNode, ToNode]) error {
	return status.Errorf(codes.Unimplemented, "method Communicate not implemented")
}
func (UnimplementedNodewardServer) ClusterAgentStream(grpc.BidiStreamingServer[FromClusterAgent, ToClusterAgent]) error {
	return status.Errorf(codes.Unimplemented, "method ClusterAgentStream not implemented")
}
func (UnimplementedNodewardServer) NodeAgentStream(grpc.BidiStreamingServer[FromNodeAgent, ToNodeAgent]) error {
	return status.Errorf(codes.Unimplemented, "method NodeAgentStream not implemented")
}
func (UnimplementedNodewardServer) ServerAgentStream(grpc.BidiStreamingServer[FromServerAgent, ToServerAgent]) error {
	return status.Errorf(codes.Unimplemented, "method ServerAgentStream not implemented")
}
func (UnimplementedNodewardServer) GetClusterAgentCredentials(context.Context, *GetClusterAgentCredentialsRequest) (*GetClusterAgentCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterAgentCredentials not implemented")
}
func (UnimplementedNodewardServer) UpdateStatus(context.Context, *UpdateStatusRequest) (*UpdateStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedNodewardServer) AddNodelog(context.Context, *AddNodelogRequest) (*AddNodelogResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddNodelog not implemented")
}
func (UnimplementedNodewardServer) GetControlPlaneNodes(context.Context, *GetControlPlaneNodesRequest) (*GetControlPlaneNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetControlPlaneNodes not implemented")
}
func (UnimplementedNodewardServer) UpdateNodeInstallationStatus(context.Context, *UpdateNodeInstallationStatusRequest) (*UpdateNodeInstallationStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNodeInstallationStatus not implemented")
}
func (UnimplementedNodewardServer) RegenerateCertificate(context.Context, *RegenerateCertificateRequest) (*RegenerateCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegenerateCertificate not implemented")
}
func (UnimplementedNodewardServer) mustEmbedUnimplementedNodewardServer() {}
func (UnimplementedNodewardServer) testEmbeddedByValue()                  {}

// UnsafeNodewardServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodewardServer will
// result in compilation errors.
type UnsafeNodewardServer interface {
	mustEmbedUnimplementedNodewardServer()
}

func RegisterNodewardServer(s grpc.ServiceRegistrar, srv NodewardServer) {
	// If the following call pancis, it indicates UnimplementedNodewardServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Nodeward_ServiceDesc, srv)
}

func _Nodeward_GetInstallVpnCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallVpnCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).GetInstallVpnCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_GetInstallVpnCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).GetInstallVpnCommands(ctx, req.(*GetInstallVpnCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_GetInstallCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstallCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).GetInstallCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_GetInstallCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).GetInstallCommands(ctx, req.(*GetInstallCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_ManualSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ManualSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).ManualSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_ManualSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).ManualSync(ctx, req.(*ManualSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_GetNodeRegistrationToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRegistrationTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).GetNodeRegistrationToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_GetNodeRegistrationToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).GetNodeRegistrationToken(ctx, req.(*GetNodeRegistrationTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_Communicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodewardServer).Communicate(&grpc.GenericServerStream[FromNode, ToNode]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_CommunicateServer = grpc.BidiStreamingServer[FromNode, ToNode]

func _Nodeward_ClusterAgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodewardServer).ClusterAgentStream(&grpc.GenericServerStream[FromClusterAgent, ToClusterAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_ClusterAgentStreamServer = grpc.BidiStreamingServer[FromClusterAgent, ToClusterAgent]

func _Nodeward_NodeAgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodewardServer).NodeAgentStream(&grpc.GenericServerStream[FromNodeAgent, ToNodeAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_NodeAgentStreamServer = grpc.BidiStreamingServer[FromNodeAgent, ToNodeAgent]

func _Nodeward_ServerAgentStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodewardServer).ServerAgentStream(&grpc.GenericServerStream[FromServerAgent, ToServerAgent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Nodeward_ServerAgentStreamServer = grpc.BidiStreamingServer[FromServerAgent, ToServerAgent]

func _Nodeward_GetClusterAgentCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterAgentCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).GetClusterAgentCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_GetClusterAgentCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).GetClusterAgentCredentials(ctx, req.(*GetClusterAgentCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_UpdateStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).UpdateStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_AddNodelog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNodelogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).AddNodelog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_AddNodelog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).AddNodelog(ctx, req.(*AddNodelogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_GetControlPlaneNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetControlPlaneNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).GetControlPlaneNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_GetControlPlaneNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).GetControlPlaneNodes(ctx, req.(*GetControlPlaneNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_UpdateNodeInstallationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeInstallationStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).UpdateNodeInstallationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_UpdateNodeInstallationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).UpdateNodeInstallationStatus(ctx, req.(*UpdateNodeInstallationStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nodeward_RegenerateCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegenerateCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodewardServer).RegenerateCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Nodeward_RegenerateCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodewardServer).RegenerateCertificate(ctx, req.(*RegenerateCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Nodeward_ServiceDesc is the grpc.ServiceDesc for Nodeward service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nodeward_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "runos.nodeward.proto.l2sec.Nodeward",
	HandlerType: (*NodewardServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInstallVpnCommands",
			Handler:    _Nodeward_GetInstallVpnCommands_Handler,
		},
		{
			MethodName: "GetInstallCommands",
			Handler:    _Nodeward_GetInstallCommands_Handler,
		},
		{
			MethodName: "ManualSync",
			Handler:    _Nodeward_ManualSync_Handler,
		},
		{
			MethodName: "GetNodeRegistrationToken",
			Handler:    _Nodeward_GetNodeRegistrationToken_Handler,
		},
		{
			MethodName: "GetClusterAgentCredentials",
			Handler:    _Nodeward_GetClusterAgentCredentials_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _Nodeward_UpdateStatus_Handler,
		},
		{
			MethodName: "AddNodelog",
			Handler:    _Nodeward_AddNodelog_Handler,
		},
		{
			MethodName: "GetControlPlaneNodes",
			Handler:    _Nodeward_GetControlPlaneNodes_Handler,
		},
		{
			MethodName: "UpdateNodeInstallationStatus",
			Handler:    _Nodeward_UpdateNodeInstallationStatus_Handler,
		},
		{
			MethodName: "RegenerateCertificate",
			Handler:    _Nodeward_RegenerateCertificate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Communicate",
			Handler:       _Nodeward_Communicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ClusterAgentStream",
			Handler:       _Nodeward_ClusterAgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "NodeAgentStream",
			Handler:       _Nodeward_NodeAgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ServerAgentStream",
			Handler:       _Nodeward_ServerAgentStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "nodeward_l2sec.proto",
}
